import { SCALE_FORMULAS } from "./scaleFormulas";

export type ScaleName =
  | "major"
  | "minor"
  | "harmonicMinor"
  | "melodicMinor"
  | "pentatonicMajor"
  | "pentatonicMinor"
  | "bluesMinor"
  | "bluesMajor"
  | "phrygian"
  | "locrian"
  | "dorian"
  | "mixolydian"
  | "lydian"
  | "wholeTone"
  | "diminishedWholeHalf"
  | "diminishedHalfWhole"
  | "augmented"
  | "doubleHarmonic"
  | "hungarianGypsy"
  | "hungarianMinor"
  | "neapolitanMinor"
  | "neapolitanMajor"
  | "persian"
  | "romanianMinor"
  | "hirajoshi"
  | "inSen"
  | "iwato"
  | "kumoi"
  | "slendro"
  | "pelog"
  | "chineseMajor"
  | "chineseMinor"
  | "ragaBhairavi"
  | "ragaKafi"
  | "balinese";
